Crash if a non-empty line in the transaction log doesn't deserialize
Fixes https://github.com/findoraorg/platform/issues/316

This also adds logging to `load_or_init` to make the errors encountered
more obvious. If there is an issue with the transaction log, the final
error will be `File exists (os error 17)` because the ledger tries 2
ways of loading the transaction log, then tries to initialize a fresh
log and merkle trees (which will fail if they already exist). Now, the
output looks like this (with `RUST_LOG=info`):

    [2020-05-05T18:16:40Z INFO  ledger::store::store] Replaying without merkle trees failed: Could not deserialize object
    [2020-05-05T18:16:40Z INFO  ledger::store::store] Checking log against merkle trees failed: Could not deserialize object
    2020/05/05  18:16:40.330 UTC  log         store             Using path /home/joe/ledger_old/block_merkle for the Merkle tree.
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError("File exists (os error 17)")', components/ledger_standalone/src/ledger_standalone.rs:19:23

So you can at least *see* the other errors.